version: "3"
services:
  jira:
    container_name: jira
    hostname: jira
    image: jira-4-testing:${JIRA_SERVICE_DESK_VERSION}
    build:
      context: .
      args:
          JIRA_SERVICE_DESK_VERSION: ${JIRA_SERVICE_DESK_VERSION}
          JAVA_VERSION: ${JAVA_VERSION}
    environment:
      - TZ
      - LC_ALL
      - LANG
      - LANGUAGE
    ports:
      - "9080:8080"
      - "9082:8081"
      - "${DEBUG_PORT}:5005"
    depends_on:
      - postgres
    networks:
      - jira-net

  postgres:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jira
    ports:
      - "5432:5432"
    networks:
      - jira-net

networks:
  jira-net:
    driver: bridge